org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=better_cushion
mod.license=MIT
mod.name=Better Cushion
mod.authors="WJiangzhi", "TingIA"
mod.contributors="ZCT Studio"
mod.version=1.0.1
mod.group=io.github.zct_studio.better_cushion
mod.description=Better Cushion improves vanilla cushions by adding physical collision, soft landing, bounce effects, and immersive particle and sound effects.
