modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/ZCT-Studio/Better_Cushion/issues"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL="https://github.com/ZCT-Studio/Better_Cushion"
authors=[${authors}]
credits='''
${contributors}
'''
description = '''
${description}
'''
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${maven_mc_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "cushionbackport"
mandatory = true
versionRange = "[${cushionsbackport_version}]"
ordering = "NONE"
side = "BOTH"
