minecraft_version=1.21.1
loader_version=0.19.3

fabric_version=0.116.13+1.21.1
neoforge_version=21.1.235

semver_mc_version_range=>=1.21 <=1.21.1
maven_mc_version_range=[1.21, 1.21.1]

cushionsbackport_version=1.0.5
