minecraft_version=26.2
loader_version=0.19.3

fabric_version=0.154.2+26.2
neoforge_version=26.2.0.12-beta

semver_mc_version_range=>=26.2 <26.3
maven_mc_version_range=[26.2,26.3)

cushionsbackport_version=1.0.5
